import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { CustomAside } from "@/components/sidebar";
import { Header } from "@/components/header";
import ProgressModal from "@/components/progress-modal";
// Import Inter font from Google Fonts
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "700"], // Specify the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${inter.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex h-screen">
            <CustomAside />
            <div className="flex-1 flex flex-col overflow-hidden">
              <Header />
              <main className="flex overflow-y-auto p-4 transition-[margin] w-full duration-300 ease-in-out group-[[data-collapsible=icon]]:ml-[--sidebar-width-icon]">
                {children}
              </main>
              <ProgressModal />
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
